//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public string ImagePath { get; set; }
        public string Title { get; set; }
        public int UserId { get; set; }
        public string Comment { get; set; }
    
        public virtual User User { get; set; }

        public System.Web.HttpPostedFileBase ImageFile { get; set; }

        public string Page { get; set; }
    }
}
