//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physiology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Physiology()
        {
            this.User_Phy = new HashSet<User_Phy>();
        }
    
        public int PhyId { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsLosing { get; set; }
        public string Comment { get; set; }
        public string AgeSnapshot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Phy> User_Phy { get; set; }
    }
}
