//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Family.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Phy
    {
        public int UserId { get; set; }
        public int PhyId { get; set; }
        public int UserPhyId { get; set; }
    
        public virtual Physiology Physiology { get; set; }
        public virtual User User { get; set; }
    }
}
